export * from './landing'
export * from './Categories'
export * from './Landscape'
export * from './SellingProducts'
export * from './Between'
export * from './Intro'
export * from './Review'
export * from './ContactUs'